version: 2 
sources: 
  - name: raw 
    schema: gz_raw_data 
    description: raw data from our greenwez company 
    tables: 
      - name: sales 
        identifier: raw_gz_sales 
        description: each product in an per order placed 
        config:
          freshness: 
            warn_after: {count: 90, period: day}
          loaded_at_field: date_date
        columns: 
          - name: date_date 
            description: date of the order placed 
            tests: 
              - not_null 
              
          - name: orders_id 
            description: unique id of order 
            tests: 
              - not_null 
              - unique: 
                  arguments: 
                    column_name: "(orders_id || '-' || pdt_id)"

      - name: products 
        identifier: raw_gz_product 
        description: one row for product 
        columns: 
          - name: products_id 
            description: unique id of the product placed 
            tests: 
              - not_null 
              - unique 
              
          - name: purchse_price 
            description: Price of the product 
            tests: 
              - not_null 
              
      - name: ship 
        identifier: raw_gz_ship 
        description: one row for ship 
        columns: 
          - name: orders_id 
            description: unique id of the order 
            tests: 
              - not_null 
              - unique 
              
          - name: shipping_fee 
            description: Price of the shipping 
            tests: 
              - not_null

      - name: adwords 
        identifier: raw_gz_adwords
        description: Google search results
        columns: 
          - name: date_date
            description: date of the order placed 
            tests: 
              - not_null 
              
          - name: paid_source 
            description: paid source 
            tests: 
              - not_null 

          - name: campaign_key
            description: campaign id 
            tests: 
              - not_null 

          - name: camPGN_name
            description: campaign name 
            tests: 
              - not_null

          - name: ads_cost
            description: sum ads cost
            tests: 
              - not_null

          - name: impression
            description: number of impressions
            tests: 
              - not_null
              
          - name: click
            description: number of clicks
            tests: 
              - not_null       


      - name: bing 
        identifier: raw_gz_bing
        description: bing search results
        columns: 
          - name: date_date
            description: date of the order placed 
            tests: 
              - not_null 
              
          - name: paid_source 
            description: paid source 
            tests: 
              - not_null 

          - name: campaign_key
            description: campaign id 
            tests: 
              - not_null 

          - name: camPGN_name
            description: campaign name 
            tests: 
              - not_null

          - name: ads_cost
            description: sum ads cost
            tests: 
              - not_null

          - name: impression
            description: number of impressions
            tests: 
              - not_null
              
          - name: click
            description: number of clicks
            tests: 
              - not_null       

      - name: criteo 
        identifier: raw_gz_criteo
        description: criteo search results
        columns: 
          - name: date_date
            description:  date of the order placed 
            tests: 
              - not_null 
              
          - name: paid_source 
            description: paid source 
            tests: 
              - not_null 

          - name: campaign_key
            description: campaign id 
            tests: 
              - not_null 

          - name: camPGN_name
            description: campaign name 
            tests: 
              - not_null

          - name: ads_cost
            description: sum ads cost
            tests: 
              - not_null

          - name: impression
            description: number of impressions
            tests: 
              - not_null
              
          - name: click
            description: number of clicks
            tests: 
              - not_null

      - name: facebook 
        identifier: raw_gz_facebook
        description: facebook search results
        columns: 
          - name: date_date
            description: date of the order placed 
            tests: 
              - not_null 
              
          - name: paid_source 
            description: paid source 
            tests: 
              - not_null 

          - name: campaign_key
            description: campaign id 
            tests: 
              - not_null 

          - name: camPGN_name
            description: campaign name 
            tests: 
              - not_null

          - name: ads_cost
            description: sum ads cost
            tests: 
              - not_null

          - name: impression
            description: number of impressions
            tests: 
              - not_null
              
          - name: click
            description: number of clicks
            tests: 
              - not_null 
models:
  - name: int_campaigns
    columns:
      - name: campaign_id
        tests: [not_null, unique]


  - name: int_campaigns_day
    description: "Daily aggregation of int_campaigns."
    columns:
      - name: date_date
        description: "Primary key (one row per day)."
        tests:
          - not_null
          - unique        